---
- name: Install Apache
  apt: name=apache2 state=present

- name: Install Apache Modules
  apache2_module: state=present name={{ item }}
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter
    - ssl

- name: Copy Apache configuration for oxid
  template: src=app.conf dest=/etc/apache2/sites-available/app.conf

- name: Enable oxid config file
  command: a2ensite app.conf
  notify: restart apache
