version: '3.2'
services:

  app_oxid6:
    image: karimfadl/apache-php72
    container_name: app_oxid6
    restart: always
    ports:
      - ${APACHE_PORT}:80
    volumes:
      - ./app:/var/www/html
      - ./config/apache/app.conf:/etc/httpd/conf.d/app.conf
    environment:
      TZ: “Europe/Berlin”


  db_oxid6:
    image: mysql:5.7
    container_name: db_oxid6
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: “Europe/Berlin”
    volumes:
      - ./databases/db_oxid6:/var/lib/mysql


  composer_oxid6:
    image: composer:1.8.4
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    container_name: composer_oxid6
    command: update --ignore-platform-reqs
    environment:
      TZ: “Europe/Berlin”


  oxid6_mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_oxid6
    restart: always
    ports:
      - ${MAILHOG_PORT}:8025
    environment:
      TZ: “Europe/Berlin”


  oxid6_adminer:
    image: adminer:latest
    container_name: oxid6_adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: db_oxid6
    environment:
      TZ: “Europe/Berlin”

