--- # This playbook will install MariaDB and create db user and give permissions.

- name: Install Mysql package
  apt: name={{ item }} state=installed
  with_items:
   - mysql-server
   - python3-mysqldb

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes

- name: Create oxid database
  mysql_db: name={{ db_name }} state=present

- name: Create oxid database user
  mysql_user: name={{ db_user }} password={{ db_password }} priv={{ db_name }}.*:ALL host=localhost state=present
