---
- name: Install Apache, PHP, Mariadb, and Oxid
  hosts: webserver
  user: ansible
  become: yes
  vars:
    ansible_become_pass: ansible
  roles:
    - system
    - apache
    - php
    - mysql
    - secure_db
    - oxid
    - ssl
